account = "0xE6F2A8d12595fBe5D410f6CA0Be13695E61C6c35"
trustNodeDepositAmount     = 1  # ether
eth2EffectiveBalance       = 32 # ether
maxPartialWithdrawalAmount = 8  # ether
gasLimit = "3000000"
maxGasPrice = "600000000000"                            #wei
batchRequestBlocksNumber = 16       # max=32
runForEntrustedLsdNetwork = false

[pinata]
apikey     = ""
pinDays = 180

[contracts]
lsdTokenAddress = ""
lsdFactoryAddress = ""

[[endpoints]]
eth1 = ""
eth2 = ""